#!/usr/bin/env bash 
#a Bash script that displays the time for 12 hours and 59 minutes
minute() {
	count=1
  while [ $count -lt 60 ]; do
         echo "$count"
	 ((count++))
  done
}
hour=0
while [ $hour -le 12 ]; do
        echo "Hour: $hour"
	case $hour in
	0|1|2|3|4|5|6|7|8|9|10|11|12)
		minute
		;;
	esac
	((hour++))
done


