#!/usr/bin/env bash
# 7-highlander

# Function to handle SIGTERM
handle_sigterm() {
    echo "I am invincible!!!"
}

# Trap SIGTERM signal
trap 'handle_sigterm' SIGTERM

# Infinite loop to print message
while true; do
    echo "To infinity and beyond"
    sleep 2
done
